using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using Talliark.Addin.Modules.CustomXml.Models;
using Excel = Microsoft.Office.Interop.Excel;

namespace Talliark.Addin.Modules.Services
{
    /// <summary>Validates and writes the rectangular Excel footprint generated by a Table link.</summary>
    internal sealed class TableExcelWriteService
    {
        public bool ConfirmCreate(
            Excel.Range anchor,
            TableGrid tableGrid,
            IList<IList<string>> cells,
            IWin32Window owner)
        {
            ValidateShape(tableGrid, cells);
            int conflicts = CountConflicts(anchor, tableGrid, oldGrid: null);
            return conflicts == 0 || ConfirmOverwrite(owner, anchor, tableGrid, conflicts);
        }

        public bool ConfirmUpdate(
            Excel.Range anchor,
            TableGrid oldGrid,
            TableGrid newGrid,
            IList<IList<string>> cells,
            IWin32Window owner)
        {
            ValidateShape(newGrid, cells);
            int conflicts = CountConflicts(anchor, newGrid, oldGrid);
            return conflicts == 0 || ConfirmOverwrite(owner, anchor, newGrid, conflicts);
        }

        public bool ConfirmCopy(
            Excel.Range firstAnchor,
            IList<(TableGrid Grid, IList<IList<string>> Cells)> tables,
            IWin32Window owner)
        {
            if (tables == null || tables.Count == 0) return false;
            if (tables[0].Grid == null)
                throw new ArgumentNullException(nameof(tables), "Copied table grid is required.");
            int columns = tables[0].Grid.ColumnCount;
            int rows = 0;
            foreach ((TableGrid Grid, IList<IList<string>> Cells) table in tables)
            {
                ValidateShape(table.Grid, table.Cells);
                if (table.Grid.ColumnCount != columns)
                    throw new ArgumentException("Copied tables must use the same columns.", nameof(tables));
                rows = checked(rows + table.Grid.RowCount);
            }

            int conflicts = CountConflicts(firstAnchor, rows, columns);
            return conflicts == 0
                || ConfirmOverwrite(owner, GetFootprint(firstAnchor, rows, columns), conflicts);
        }

        public void WriteCreate(
            Excel.Range anchor, TableGrid tableGrid, IList<IList<string>> cells)
        {
            ValidateShape(tableGrid, cells);
            WriteCells(anchor, tableGrid, cells);
        }

        public void Rewrite(
            Excel.Range anchor,
            TableGrid oldGrid,
            TableGrid newGrid,
            IList<IList<string>> cells)
        {
            ValidateShape(newGrid, cells);
            Clear(anchor, oldGrid);
            WriteCells(anchor, newGrid, cells);
        }

        public void Clear(Excel.Range anchor, TableGrid tableGrid)
        {
            if (anchor == null || tableGrid == null) return;
            Excel.Application app = anchor.Application as Excel.Application;
            bool previousEvents = app?.EnableEvents ?? true;
            try
            {
                if (app != null) app.EnableEvents = false;
                GetFootprint(anchor, tableGrid).ClearContents();
            }
            finally
            {
                if (app != null) app.EnableEvents = previousEvents;
            }
        }

        private static void WriteCells(
            Excel.Range anchor, TableGrid tableGrid, IList<IList<string>> cells)
        {
            int rows = tableGrid.RowCount;
            int columns = tableGrid.ColumnCount;
            var values = new object[rows, columns];
            var formats = new string[rows, columns];

            // Parsing is inexpensive managed work. Build both matrices before crossing the
            // Excel COM boundary so values can be written in one operation and formatting
            // can be applied to a small number of contiguous blocks.
            for (int row = 0; row < rows; row++)
            {
                for (int column = 0; column < columns; column++)
                {
                    string sourceText = cells[row][column] ?? string.Empty;
                    values[row, column] = TextValueFormatter.FormatAuto(sourceText);
                    formats[row, column] = CellFormattingService.GetAutoNumberFormat(sourceText);
                }
            }

            Excel.Application app = anchor.Application as Excel.Application;
            bool previousEvents = app?.EnableEvents ?? true;
            try
            {
                if (app != null) app.EnableEvents = false;
                Excel.Range footprint = GetFootprint(anchor, rows, columns);
                footprint.Value2 = values;
                ApplyNumberFormats(anchor, footprint, formats, rows, columns);
            }
            finally
            {
                if (app != null) app.EnableEvents = previousEvents;
            }
        }

        private static int CountConflicts(
            Excel.Range anchor, TableGrid newGrid, TableGrid oldGrid)
        {
            int rows = newGrid.RowCount;
            int columns = newGrid.ColumnCount;
            try
            {
                object formulas = GetFootprint(anchor, rows, columns).Formula;
                return CountConflicts(
                    formulas,
                    rows,
                    columns,
                    (row, column) => oldGrid == null
                        || row >= oldGrid.RowCount
                        || column >= oldGrid.ColumnCount);
            }
            catch (COMException)
            {
                // If Excel refuses the bulk read, conservatively treat every newly-covered
                // cell as occupied, matching the previous per-cell behavior.
                int conflicts = 0;
                for (int row = 0; row < rows; row++)
                {
                    for (int column = 0; column < columns; column++)
                    {
                        if (oldGrid == null
                            || row >= oldGrid.RowCount
                            || column >= oldGrid.ColumnCount)
                            conflicts++;
                    }
                }
                return conflicts;
            }
        }

        private static int CountConflicts(Excel.Range anchor, int rows, int columns)
        {
            try
            {
                object formulas = GetFootprint(anchor, rows, columns).Formula;
                return CountConflicts(formulas, rows, columns, (row, column) => true);
            }
            catch (COMException)
            {
                return checked(rows * columns);
            }
        }

        private static int CountConflicts(
            object formulas,
            int rows,
            int columns,
            Func<int, int, bool> shouldInspect)
        {
            var matrix = formulas as object[,];
            int conflicts = 0;
            for (int row = 0; row < rows; row++)
            {
                for (int column = 0; column < columns; column++)
                {
                    if (!shouldInspect(row, column)) continue;

                    object formula = matrix == null
                        ? formulas
                        : matrix[row + matrix.GetLowerBound(0), column + matrix.GetLowerBound(1)];
                    if (formula != null && !string.IsNullOrWhiteSpace(formula.ToString()))
                        conflicts++;
                }
            }
            return conflicts;
        }

        private static void ApplyNumberFormats(
            Excel.Range anchor,
            Excel.Range footprint,
            string[,] formats,
            int rows,
            int columns)
        {
            string firstFormat = formats[0, 0];
            bool allSame = true;
            for (int row = 0; row < rows && allSame; row++)
            {
                for (int column = 0; column < columns; column++)
                {
                    if (!string.Equals(firstFormat, formats[row, column], StringComparison.Ordinal))
                    {
                        allSame = false;
                        break;
                    }
                }
            }

            if (allSame)
            {
                footprint.NumberFormat = firstFormat;
                return;
            }

            // Reset formats overwritten by the table, then coalesce equal horizontal runs
            // across adjacent rows. Typical financial tables collapse to only a handful of
            // COM formatting calls even when they contain hundreds of cells.
            footprint.NumberFormat = "General";
            var active = new Dictionary<FormatRunKey, FormatBlock>();
            var completed = new List<FormatBlock>();

            for (int row = 0; row < rows; row++)
            {
                var next = new Dictionary<FormatRunKey, FormatBlock>();
                int column = 0;
                while (column < columns)
                {
                    string format = formats[row, column];
                    int startColumn = column;
                    while (column + 1 < columns
                        && string.Equals(format, formats[row, column + 1], StringComparison.Ordinal))
                        column++;

                    int columnCount = column - startColumn + 1;
                    if (!string.Equals(format, "General", StringComparison.Ordinal))
                    {
                        var key = new FormatRunKey(startColumn, columnCount, format);
                        if (active.TryGetValue(key, out FormatBlock block))
                        {
                            block.RowCount++;
                            next[key] = block;
                            active.Remove(key);
                        }
                        else
                        {
                            next[key] = new FormatBlock(row, startColumn, columnCount, format);
                        }
                    }
                    column++;
                }

                completed.AddRange(active.Values);
                active = next;
            }
            completed.AddRange(active.Values);

            foreach (FormatBlock block in completed)
            {
                Excel.Range start = anchor.get_Offset(block.StartRow, block.StartColumn);
                start.get_Resize(block.RowCount, block.ColumnCount).NumberFormat = block.Format;
            }
        }

        private sealed class FormatBlock
        {
            public FormatBlock(int startRow, int startColumn, int columnCount, string format)
            {
                StartRow = startRow;
                StartColumn = startColumn;
                RowCount = 1;
                ColumnCount = columnCount;
                Format = format;
            }

            public int StartRow { get; }
            public int StartColumn { get; }
            public int RowCount { get; set; }
            public int ColumnCount { get; }
            public string Format { get; }
        }

        private sealed class FormatRunKey : IEquatable<FormatRunKey>
        {
            public FormatRunKey(int startColumn, int columnCount, string format)
            {
                StartColumn = startColumn;
                ColumnCount = columnCount;
                Format = format;
            }

            public int StartColumn { get; }
            public int ColumnCount { get; }
            public string Format { get; }

            public bool Equals(FormatRunKey other)
            {
                return other != null
                    && StartColumn == other.StartColumn
                    && ColumnCount == other.ColumnCount
                    && string.Equals(Format, other.Format, StringComparison.Ordinal);
            }

            public override bool Equals(object obj) => Equals(obj as FormatRunKey);

            public override int GetHashCode()
            {
                unchecked
                {
                    int hash = StartColumn;
                    hash = (hash * 397) ^ ColumnCount;
                    hash = (hash * 397) ^ (Format?.GetHashCode() ?? 0);
                    return hash;
                }
            }
        }

        private static bool ConfirmOverwrite(
            IWin32Window owner, Excel.Range anchor, TableGrid grid, int conflictCount)
        {
            return ConfirmOverwrite(owner, GetFootprint(anchor, grid), conflictCount);
        }

        private static bool ConfirmOverwrite(
            IWin32Window owner, Excel.Range footprint, int conflictCount)
        {
            string rangeAddress = footprint.Address;
            DialogResult first = MessageBox.Show(
                owner,
                $"The table would overwrite {conflictCount} existing cell(s) in {rangeAddress}.\n\nContinue?",
                "Talliark – Table Conflict",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Warning,
                MessageBoxDefaultButton.Button2);
            if (first != DialogResult.Yes) return false;

            DialogResult second = MessageBox.Show(
                owner,
                "Continuing will permanently replace the existing values or formulas.\n\nConfirm overwrite?",
                "Talliark – Confirm Overwrite",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Warning,
                MessageBoxDefaultButton.Button2);
            return second == DialogResult.Yes;
        }

        internal static Excel.Range GetFootprint(Excel.Range anchor, TableGrid grid)
        {
            return anchor.get_Resize(grid.RowCount, grid.ColumnCount);
        }

        internal static Excel.Range GetFootprint(Excel.Range anchor, int rows, int columns)
        {
            return anchor.get_Resize(rows, columns);
        }

        private static void ValidateShape(TableGrid tableGrid, IList<IList<string>> cells)
        {
            if (tableGrid == null) throw new ArgumentNullException(nameof(tableGrid));
            if (cells == null || cells.Count != tableGrid.RowCount)
                throw new ArgumentException("Table cell rows do not match the row boundaries.", nameof(cells));

            foreach (IList<string> row in cells)
            {
                if (row == null || row.Count != tableGrid.ColumnCount)
                    throw new ArgumentException("Table cell columns do not match the column boundaries.", nameof(cells));
            }
        }
    }
}
