#Requires -Version 5.1
<#
  Writes Properties\GeneratedVersion.cs with the given version string.
  Called by the GenerateVersionFile MSBuild target before CoreCompile.
  For normal builds the version is "dev"; installer builds pass the real version.
#>
param(
    [Parameter(Mandatory)][string]$Version,
    [Parameter(Mandatory)][string]$OutputPath
)

$content = @"
// Auto-generated by the build — do not edit manually.
namespace DocuLink.Addin
{
    internal static class AppVersion
    {
        public const string Current = "$Version";
    }
}
"@

Set-Content -Path $OutputPath -Value $content -Encoding UTF8
