using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using DocuLink.Addin.Modules.CustomXml.Models;
using Excel = Microsoft.Office.Interop.Excel;

namespace DocuLink.Addin.Modules.Services
{
    /// <summary>Validates and writes the rectangular Excel footprint generated by a Table link.</summary>
    internal sealed class TableExcelWriteService
    {
        public bool ConfirmCreate(
            Excel.Range anchor,
            TableGrid tableGrid,
            IList<IList<string>> cells,
            IWin32Window owner)
        {
            ValidateShape(tableGrid, cells);
            int conflicts = CountConflicts(anchor, tableGrid, oldGrid: null);
            return conflicts == 0 || ConfirmOverwrite(owner, anchor, tableGrid, conflicts);
        }

        public bool ConfirmUpdate(
            Excel.Range anchor,
            TableGrid oldGrid,
            TableGrid newGrid,
            IList<IList<string>> cells,
            IWin32Window owner)
        {
            ValidateShape(newGrid, cells);
            int conflicts = CountConflicts(anchor, newGrid, oldGrid);
            return conflicts == 0 || ConfirmOverwrite(owner, anchor, newGrid, conflicts);
        }

        public void WriteCreate(
            Excel.Range anchor, TableGrid tableGrid, IList<IList<string>> cells)
        {
            ValidateShape(tableGrid, cells);
            WriteCells(anchor, tableGrid, cells);
        }

        public void Rewrite(
            Excel.Range anchor,
            TableGrid oldGrid,
            TableGrid newGrid,
            IList<IList<string>> cells)
        {
            ValidateShape(newGrid, cells);
            Clear(anchor, oldGrid);
            WriteCells(anchor, newGrid, cells);
        }

        public void Clear(Excel.Range anchor, TableGrid tableGrid)
        {
            if (anchor == null || tableGrid == null) return;
            Excel.Application app = anchor.Application as Excel.Application;
            bool previousEvents = app?.EnableEvents ?? true;
            try
            {
                if (app != null) app.EnableEvents = false;
                GetFootprint(anchor, tableGrid).ClearContents();
            }
            finally
            {
                if (app != null) app.EnableEvents = previousEvents;
            }
        }

        private static void WriteCells(
            Excel.Range anchor, TableGrid tableGrid, IList<IList<string>> cells)
        {
            Excel.Application app = anchor.Application as Excel.Application;
            bool previousEvents = app?.EnableEvents ?? true;
            try
            {
                if (app != null) app.EnableEvents = false;
                for (int row = 0; row < tableGrid.RowCount; row++)
                {
                    for (int column = 0; column < tableGrid.ColumnCount; column++)
                    {
                        Excel.Range cell = (Excel.Range)anchor.Cells[row + 1, column + 1];
                        string sourceText = cells[row][column] ?? string.Empty;
                        cell.Value2 = TextValueFormatter.FormatAuto(sourceText);
                        CellFormattingService.ApplyAutoNumberFormat(cell, sourceText);
                    }
                }
            }
            finally
            {
                if (app != null) app.EnableEvents = previousEvents;
            }
        }

        private static int CountConflicts(
            Excel.Range anchor, TableGrid newGrid, TableGrid oldGrid)
        {
            int conflicts = 0;
            for (int row = 0; row < newGrid.RowCount; row++)
            {
                for (int column = 0; column < newGrid.ColumnCount; column++)
                {
                    bool belongsToOldFootprint = oldGrid != null
                        && row < oldGrid.RowCount
                        && column < oldGrid.ColumnCount;
                    if (belongsToOldFootprint) continue;

                    Excel.Range cell = (Excel.Range)anchor.Cells[row + 1, column + 1];
                    if (HasContent(cell)) conflicts++;
                }
            }
            return conflicts;
        }

        private static bool HasContent(Excel.Range cell)
        {
            try
            {
                object formula = cell.Formula;
                if (formula != null && !string.IsNullOrWhiteSpace(formula.ToString())) return true;
                object value = cell.Value2;
                return value != null && !string.IsNullOrWhiteSpace(value.ToString());
            }
            catch (COMException)
            {
                // If Excel refuses the read, conservatively treat the cell as occupied.
                return true;
            }
        }

        private static bool ConfirmOverwrite(
            IWin32Window owner, Excel.Range anchor, TableGrid grid, int conflictCount)
        {
            string rangeAddress = GetFootprint(anchor, grid).Address;
            DialogResult first = MessageBox.Show(
                owner,
                $"The table would overwrite {conflictCount} existing cell(s) in {rangeAddress}.\n\nContinue?",
                "DocuLink – Table Conflict",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Warning,
                MessageBoxDefaultButton.Button2);
            if (first != DialogResult.Yes) return false;

            DialogResult second = MessageBox.Show(
                owner,
                "Continuing will permanently replace the existing values or formulas.\n\nConfirm overwrite?",
                "DocuLink – Confirm Overwrite",
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Warning,
                MessageBoxDefaultButton.Button2);
            return second == DialogResult.Yes;
        }

        internal static Excel.Range GetFootprint(Excel.Range anchor, TableGrid grid)
        {
            return anchor.get_Resize(grid.RowCount, grid.ColumnCount);
        }

        private static void ValidateShape(TableGrid tableGrid, IList<IList<string>> cells)
        {
            if (tableGrid == null) throw new ArgumentNullException(nameof(tableGrid));
            if (cells == null || cells.Count != tableGrid.RowCount)
                throw new ArgumentException("Table cell rows do not match the row boundaries.", nameof(cells));

            foreach (IList<string> row in cells)
            {
                if (row == null || row.Count != tableGrid.ColumnCount)
                    throw new ArgumentException("Table cell columns do not match the column boundaries.", nameof(cells));
            }
        }
    }
}
